version: 2.1
commands:
  build_image:
    description: "Build docker image for specific arch"
    parameters:
      arch:
        type: string
    steps:
      - checkout
      - run: |
          docker version
          docker run --rm --privileged multiarch/qemu-user-static:register
          make << parameters.arch >>
          echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin
          docker push cinemast/hello-docker-multiarch:<< parameters.arch >>-latest
jobs:
  "build-amd64":
    machine: true
    steps:
      - build_image:
          arch: amd64
  "build-arm64v8":
    machine: true
    steps:
      - build_image:
          arch: arm64v8
  "build-arm32v6":
    machine: true
    steps:
      - build_image:
          arch: arm32v6
workflows:
  version: 2
  build:
    jobs:
      - "build-amd64"
      - "build-arm64v8"
      - "build-arm32v6"