version: 2.1
commands:
  buildImage:
    description: "Build docker image for specific arch"
    parameters:
      arch:
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.09.3
      - run: |
          apk add make docker
          make << parameters.arch >>
          echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin
          docker push cinemast/hello-docker-multiarch:<< parameters.arch >>-latest
jobs:
  "build-amd64":
    docker:
      - image: alpine:latest
    steps:
      - buildImage:
          arch: amd64
  "build-arm64v8":
    docker:
      - image: alpine:latest
    steps:
      - buildImage:
          arch: arm64v8
  "build-arm32v6":
    docker:
      - image: alpine:latest
    steps:
      - buildImage:
          arch: arm32v6
workflows:
  version: 2
  build:
    jobs:
      - "build-amd64"
      - "build-arm64v8"
      - "build-arm32v6"