version: 2.1
jobs:
  "build-amd64":
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          apk add make docker
          make amd64
          echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
          docker push cinemast/hello-docker-multiarch:amd64-latest
workflows:
  version: 2
  build:
    jobs:
      - "build-amd64"